version: '3'
services:
  tesseract:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - TAG=humble-0.21
        - ROS_DISTRO=humble
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: $XAUTHORITY
      NVIDIA_DRIVER_CAPABILITIES: all
      ROS_LOG_DIR: /tmp
    container_name: snp
    image: ghcr.io/ros-industrial-consortium/scan_n_plan_workshop:humble-latest
    stdin_open: true
    tty: true
    network_mode: host
    user: ${CURRENT_UID}  # CURRENT_UID=$(id -u):$(id -g)
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/hosts:/etc/hosts
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
