# Anchors
DoneTask: &done
  class: DoneTaskFactory
  config:
    conditional: false
AbortTask: &abort
  class: AbortTaskFactory
  config:
    conditional: false
MinLengthTask: &min_length
  class: MinLengthTaskFactory
  config:
    conditional: true
    inputs: [input_data]
    outputs: [output_data]
    format_result_as_input: false
TrajOptMotionPlannerTask: &trajopt
  class: TrajOptMotionPlannerTaskFactory
  config:
    conditional: true
    inputs: [output_data]
    outputs: [output_data]
    format_result_as_input: false
DiscreteContactCheckTask: &contact_check
  class: DiscreteContactCheckTaskFactory
  config:
    conditional: true
    inputs: [output_data]
ConstantTCPSpeedTimeParameterizationTask: &constant_tcp_speed
  class: ConstantTCPSpeedTimeParameterizationTaskFactory
  config:
    conditional: true
    inputs: [output_data]
    outputs: [output_data]
IterativeSplineParameterizationTask: &isp
  class: IterativeSplineParameterizationTaskFactory
  config:
    conditional: true
    inputs: [output_data]
    outputs: [output_data]
KinematicLimitsCheckTask: &limits_check
  class: KinematicLimitsCheckTaskFactory
  config:
    conditional: true
    inputs: [output_data]
    outputs: [output_data]

# Task composer configuration
task_composer_plugins:
  search_libraries:
    - snp_motion_planning_tasks
  executors:
    default: TaskflowExecutor
    plugins:
      TaskflowExecutor:
        class: TaskflowTaskComposerExecutorFactory
        config:
          threads: 8
  tasks:
    plugins:    
      SNPCartesianPipeline:
        class: GraphTaskFactory
        config:
          inputs: [input_data]
          outputs: [output_data]
          nodes:
            DoneTask: *done
            AbortTask: *abort
            MinLengthTask: *min_length
            TrajOptMotionPlannerTask: *trajopt
            DiscreteContactCheckTask: *contact_check
            ConstantTCPSpeedTimeParameterizationTask: *constant_tcp_speed
            KinematicLimitsCheckTask: *limits_check
          edges:
            - source: MinLengthTask
              destinations: [AbortTask, TrajOptMotionPlannerTask]
            - source: TrajOptMotionPlannerTask
              destinations: [AbortTask, DiscreteContactCheckTask]
            - source: DiscreteContactCheckTask
              destinations: [AbortTask, ConstantTCPSpeedTimeParameterizationTask]
            - source: ConstantTCPSpeedTimeParameterizationTask # IterativeSplineParameterizationTask
              destinations: [AbortTask, KinematicLimitsCheckTask]
            - source: KinematicLimitsCheckTask
              destinations: [AbortTask, DoneTask]
          terminals: [AbortTask, DoneTask]
      SNPFreespacePipeline:
        class: GraphTaskFactory
        config:
          inputs: [input_data]
          outputs: [output_data]
          nodes:
            DoneTask: *done
            AbortTask: *abort
            MinLengthTask: *min_length
            OMPLMotionPlannerTask:
              class: OMPLMotionPlannerTaskFactory
              config:
                conditional: true
                inputs: [output_data]
                outputs: [output_data]
                format_result_as_input: true
            TrajOptMotionPlannerTask: *trajopt
            DiscreteContactCheckTask: *contact_check
            IterativeSplineParameterizationTask: *isp
            KinematicLimitsCheckTask: *limits_check
          edges:
            - source: MinLengthTask
              destinations: [AbortTask, OMPLMotionPlannerTask]
            - source: OMPLMotionPlannerTask
              destinations: [AbortTask, TrajOptMotionPlannerTask]
            - source: TrajOptMotionPlannerTask
              destinations: [AbortTask, DiscreteContactCheckTask]
            - source: DiscreteContactCheckTask
              destinations: [AbortTask, IterativeSplineParameterizationTask]
            - source: IterativeSplineParameterizationTask
              destinations: [AbortTask, KinematicLimitsCheckTask]
            - source: KinematicLimitsCheckTask
              destinations: [AbortTask, DoneTask]
          terminals: [AbortTask, DoneTask]
      SNPTransitionPipeline:
        class: GraphTaskFactory
        config:
          inputs: [input_data]
          outputs: [output_data]
          nodes:
            DoneTask: *done
            AbortTask: *abort
            MinLengthTask: *min_length
            TrajOptMotionPlannerTask: *trajopt
            OMPLMotionPlannerTask:
              class: OMPLMotionPlannerTaskFactory
              config:
                conditional: true
                inputs: [output_data]
                outputs: [output_data]
                format_result_as_input: false
            DiscreteContactCheckTask: *contact_check
            IterativeSplineParameterizationTask: *isp
            KinematicLimitsCheckTask: *limits_check
          edges:
            - source: MinLengthTask
              destinations: [AbortTask, TrajOptMotionPlannerTask]
            - source: TrajOptMotionPlannerTask
              destinations: [OMPLMotionPlannerTask, DiscreteContactCheckTask]
            - source: OMPLMotionPlannerTask
              destinations: [AbortTask, DiscreteContactCheckTask]
            - source: DiscreteContactCheckTask
              destinations: [AbortTask, IterativeSplineParameterizationTask]
            - source: IterativeSplineParameterizationTask
              destinations: [AbortTask, KinematicLimitsCheckTask]
            - source: KinematicLimitsCheckTask
              destinations: [AbortTask, DoneTask]
          terminals: [AbortTask, DoneTask]
      SNPPipeline:
        class: GraphTaskFactory
        config:
          inputs: [input_data]
          outputs: [output_data]
          nodes:
            DoneTask: *done
            AbortTask: *abort
            SimpleMotionPlannerTask:
              class: SimpleMotionPlannerTaskFactory
              config:
                conditional: true
                inputs: [input_data]
                outputs: [output_data]
                format_result_as_input: true
            DescartesMotionPlannerTask:
              class: DescartesFMotionPlannerTaskFactory
              config:
                conditional: true
                inputs: [output_data]
                outputs: [output_data]
                format_result_as_input: true
            RasterMotionTask:
              class: RasterMotionTaskFactory
              config:
                conditional: true
                inputs: [output_data]
                outputs: [output_data]
                freespace:
                  task: SNPFreespacePipeline
                  config:
                    input_remapping:
                      input_data: output_data
                    output_remapping:
                      output_data: output_data
                    input_indexing: [output_data]
                    output_indexing: [output_data]
                raster:
                  task: SNPCartesianPipeline
                  config:
                    input_remapping:
                      input_data: output_data
                    output_remapping:
                      output_data: output_data
                    input_indexing: [output_data]
                    output_indexing: [output_data]
                transition:
                  task: SNPTransitionPipeline
                  config:
                    input_remapping:
                      input_data: output_data
                    output_remapping:
                      output_data: output_data
                    input_indexing: [output_data]
                    output_indexing: [output_data]
          edges:
            - source: SimpleMotionPlannerTask
              destinations: [AbortTask, DescartesMotionPlannerTask]
            - source: DescartesMotionPlannerTask
              destinations: [AbortTask, RasterMotionTask]
            - source: RasterMotionTask
              destinations: [AbortTask, DoneTask]
          terminals: [AbortTask, DoneTask]
