name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - released
  schedule:
    - cron: '0 5 * * *'

jobs:
  ci:
    name: ${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [foxy, humble, rolling]
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker meta-information
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=ref,event=branch,prefix=${{ matrix.distro }}-
            type=semver,pattern={{major}}.{{minor}},prefix=${{ matrix.distro }}-

      - name: Build repository
        uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: ${{ matrix.distro }}
          ROS_REPO: main
          BEFORE_INIT: ''
          PREFIX: ${{ github.repository }}_
          DOCKER_IMAGE: ghcr.io/tesseract-robotics/tesseract_ros2:${{ matrix.distro }}-0.20
          GIT_SUBMODULE_STRATEGY: normal
          BUILDER: colcon
          ADDITIONAL_DEBS: 'libxmlrpcpp-dev'
          UNDERLAY: /root/tesseract-robotics/tesseract_ros2_target_ws/install
          UPSTREAM_WORKSPACE: dependencies_${{ matrix.distro }}.repos
          BEFORE_BUILD_UPSTREAM_WORKSPACE_EMBED: 'ici_with_unset_variables source /opt/ros/${ROS_DISTRO}/setup.bash'
          BEFORE_RUN_TARGET_TEST_EMBED: ''
          ROSDEP_SKIP_KEYS: "tesseract_rviz tesseract_plugins rviz octomap_ros libvtk"
          AFTER_SCRIPT: 'rm -r $BASEDIR/${PREFIX}upstream_ws/build $BASEDIR/${PREFIX}target_ws/build'
          DOCKER_COMMIT: ${{ steps.meta.outputs.tags }}

      - name: Push post-build Docker
        if: ${{ github.ref == 'refs/heads/master' || github.event_name == 'release' }}
        run: docker push ${{ steps.meta.outputs.tags }}
